### ISSUE TITLE
Enviar Email

### ISSUE THREAD

**Issue by Dark1nessss** [Dark1nessss/Project-Car#38]
Estou a testar enviar emails com: https://formsubmit.co , esta a dar um erro que nao devia estar a dar...

Resumindo é necessario ter um method="POST" onde existe uma action com o link da domain deles+o email que queremos q envie as informacoes...

```
		<section id="forms" class="forms">
			<div class="container">
				<div class="forms-above-text">
                    <span>Contact Us</span>
					<h3 class="forms-h3">Have any adittional questions? Feel free to chat whit us via email</h3>
                </div>
					<div class="forms-area">
                    <form action="https://formsubmit.co/dmytro@my.istec.pt" method="POST">
						<div class="form-group">
							<label for="subject">Subject:</label>
							<input type="text" id="subject" name="subject" required>
						</div>
						<div class="form-group">
							<label for="email">Email:</label>
							<input type="email" id="email" name="email" autocomplete="off" required>
						</div>
						<div class="form-group">
							<label for="message">Message:</label>
							<textarea id="message" name="message" rows="5" required></textarea>
						</div>
                        <a href="submit" class="btn">Submit</a>
					</form>
				</div>
			</div>
		</section>
```

Video usado para setup: https://www.youtube.com/watch?v=FrfEWFO4VzM

Erro existente quando se clica no botao submit:

![Captura de ecrã 2024-06-14 215058](https://github.com/Dark1nessss/Project-Car/assets/83649643/cb710d1b-f563-4c3d-a8ad-5a6814e57f54)

Isto tudo pode ser encontrado em: https://github.com/Dark1nessss/Project-Car/tree/Dashboard-Develop

**Comment by tskxz** [comment]
> Estou a testar enviar emails com: https://formsubmit.co , esta a dar um erro que nao devia estar a dar...
> 
> Resumindo é necessario ter um method="POST" onde existe uma action com o link da domain deles+o email que queremos q envie as informacoes...
> 
> ```
> 		<section id="forms" class="forms">
> 			<div class="container">
> 				<div class="forms-above-text">
>                     <span>Contact Us</span>
> 					<h3 class="forms-h3">Have any adittional questions? Feel free to chat whit us via email</h3>
>                 </div>
> 					<div class="forms-area">
>                     <form action="https://formsubmit.co/dmytro@my.istec.pt" method="POST">
> 						<div class="form-group">
> 							<label for="subject">Subject:</label>
> 							<input type="text" id="subject" name="subject" required>
> 						</div>
> 						<div class="form-group">
> 							<label for="email">Email:</label>
> 							<input type="email" id="email" name="email" autocomplete="off" required>
> 						</div>
> 						<div class="form-group">
> 							<label for="message">Message:</label>
> 							<textarea id="message" name="message" rows="5" required></textarea>
> 						</div>
>                         <a href="submit" class="btn">Submit</a>
> 					</form>
> 				</div>
> 			</div>
> 		</section>
> ```
> 
> Video usado para setup: https://www.youtube.com/watch?v=FrfEWFO4VzM
> 
> Erro existente quando se clica no botao submit:
> 
> ![Captura de ecrã 2024-06-14 215058](https://private-user-images.githubusercontent.com/83649643/339901470-cb710d1b-f563-4c3d-a8ad-5a6814e57f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDcyMDAsIm5iZiI6MTcxODQ0NjkwMCwicGF0aCI6Ii84MzY0OTY0My8zMzk5MDE0NzAtY2I3MTBkMWItZjU2My00YzNkLWE4YWQtNWE2ODE0ZTU3ZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEwMjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MWJiMWI2NDFlYTUxZGVhMzE4MGVjZmEyZGM2ZjMxZTk4Njk3ZGUwZmJkMGZjOTU4ZjkzNzYyMWY4MmIxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DdEOgy1KRX9-Du8Tn0_A71rQZ9IMH6ZRVi85qF0Iigk)
> 
> Isto tudo pode ser encontrado em: https://github.com/Dark1nessss/Project-Car/tree/Dashboard-Develop

Pelos vistos, a seguinte linha tenta redirecionar para a pagina "submit"
`<a href="submit" class="btn">Submit</a>`
Mudei para `<button type="submit" class="btn">Submit</button>` e depois de submeter a mensagem, aparece
![image](https://github.com/Dark1nessss/Project-Car/assets/47666341/25f2c4cc-6c18-4343-90c4-2514009dca37)
