### ISSUE TITLE
ReferenceError: data_nascimento is not defined

### ISSUE THREAD

**Issue by tskxz** [Dark1nessss/Project-Car#55]
Se irmos para a pagina /profile, aparece de vez em quando o seguinte erro:
![image](https://github.com/Dark1nessss/Project-Car/assets/47666341/55566a14-0088-440a-b555-d4c6b9f9202d)

**Comment by Dark1nessss** [comment]
O problema estava no ; que nao existia:


codigo antigo:

```
router.get('/profile', function(req, res, next){
  if(req.session.loggedIn){
    res.render('profile', {
      cliente_id: req.session.cliente_id,
      nome_cliente: req.session.nome_cliente,
      email_cliente: req.session.email_cliente,
      morada_cliente: req.session.morada_cliente,
      nif_cliente: req.session.nif_cliente,
      foto_perfil: req.session.foto_perfil,
      data_nascimento: req.session.data_nascimento,
      success: req.flash("success")
    })
    console.log(data_nascimento)
  } else {
    res.redirect("/login");
  }
  
})
```

codigo novo:

```
router.get('/profile', function(req, res, next){
  if(req.session.loggedIn){
    res.render('profile', {
      cliente_id: req.session.cliente_id,
      nome_cliente: req.session.nome_cliente,
      email_cliente: req.session.email_cliente,
      morada_cliente: req.session.morada_cliente,
      nif_cliente: req.session.nif_cliente,
      foto_perfil: req.session.foto_perfil,
      data_nascimento: req.session.data_nascimento,
      success: req.flash("success")
    });
  } else {
    res.redirect("/login");
  }
});
```

**Comment by tskxz** [comment]
> O problema estava no ; que nao existia:
> 
> codigo antigo:
> 
> ```
> router.get('/profile', function(req, res, next){
>   if(req.session.loggedIn){
>     res.render('profile', {
>       cliente_id: req.session.cliente_id,
>       nome_cliente: req.session.nome_cliente,
>       email_cliente: req.session.email_cliente,
>       morada_cliente: req.session.morada_cliente,
>       nif_cliente: req.session.nif_cliente,
>       foto_perfil: req.session.foto_perfil,
>       data_nascimento: req.session.data_nascimento,
>       success: req.flash("success")
>     })
>     console.log(data_nascimento)
>   } else {
>     res.redirect("/login");
>   }
>   
> })
> ```
> 
> codigo novo:
> 
> ```
> router.get('/profile', function(req, res, next){
>   if(req.session.loggedIn){
>     res.render('profile', {
>       cliente_id: req.session.cliente_id,
>       nome_cliente: req.session.nome_cliente,
>       email_cliente: req.session.email_cliente,
>       morada_cliente: req.session.morada_cliente,
>       nif_cliente: req.session.nif_cliente,
>       foto_perfil: req.session.foto_perfil,
>       data_nascimento: req.session.data_nascimento,
>       success: req.flash("success")
>     });
>   } else {
>     res.redirect("/login");
>   }
> });
> ```

impossivel :sob:

**Comment by Dark1nessss** [comment]
> > O problema estava no ; que nao existia:
> > codigo antigo:
> > ```
> > router.get('/profile', function(req, res, next){
> >   if(req.session.loggedIn){
> >     res.render('profile', {
> >       cliente_id: req.session.cliente_id,
> >       nome_cliente: req.session.nome_cliente,
> >       email_cliente: req.session.email_cliente,
> >       morada_cliente: req.session.morada_cliente,
> >       nif_cliente: req.session.nif_cliente,
> >       foto_perfil: req.session.foto_perfil,
> >       data_nascimento: req.session.data_nascimento,
> >       success: req.flash("success")
> >     })
> >     console.log(data_nascimento)
> >   } else {
> >     res.redirect("/login");
> >   }
> >   
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > codigo novo:
> > ```
> > router.get('/profile', function(req, res, next){
> >   if(req.session.loggedIn){
> >     res.render('profile', {
> >       cliente_id: req.session.cliente_id,
> >       nome_cliente: req.session.nome_cliente,
> >       email_cliente: req.session.email_cliente,
> >       morada_cliente: req.session.morada_cliente,
> >       nif_cliente: req.session.nif_cliente,
> >       foto_perfil: req.session.foto_perfil,
> >       data_nascimento: req.session.data_nascimento,
> >       success: req.flash("success")
> >     });
> >   } else {
> >     res.redirect("/login");
> >   }
> > });
> > ```
> 
> impossivel 😭

Mais q possivel :)

**Comment by tskxz** [comment]
![image](https://github.com/user-attachments/assets/416e40ba-30c3-4f08-9cfb-13fa4ecc83b7)
